### ISSUE TITLE
Crash over and over by starting in to the Server

### ISSUE THREAD

**Issue by D3VILSWOLF** [Kilichi/ks_peds#4]
Hi i use the Qbus (qb-Core files and when he load the ressource from this menu it is get crashed over and over again i cant do nithing. 
Hope u have any idea i wish i can get a free ped changer but i dont find anyone he work on Qbcore and it is very sad atm. Thanks for ur time.

**Comment by Kilichi** [comment]
Hi can you send me a message in discord is better than this and i cand
explaind you what its better :)
Discord: Kilichi#2284

**Comment by D3VILSWOLF** [comment]
Friendrequest sendet
